### ISSUE TITLE
--clean: Add comments and empty lines like in original strings.xml

### ISSUE THREAD

**Issue by gsantner** [jordanjoz1/android-localization-helper#3]
Thanks for this tool!

Currently the clean command remove comments. I would expect it to keep (or add if not existing) comments and empty lines just like in the original strings\*.xml.

Example below: There is no comment and empty line above the "no_valid_path" in the translated strings.

![gnome-shell-screenshot-dhlq0y](https://cloud.githubusercontent.com/assets/6735650/26564460/522350da-44e1-11e7-8eb8-c8aad4dc371d.png)

![gnome-shell-screenshot-qg930y](https://cloud.githubusercontent.com/assets/6735650/26564470/68e67b80-44e1-11e7-8ce3-a019ec8a4a26.png)

**Comment by jordanjoz1** [comment]
I'm glad you're finding it useful! Good find. I think I originally didn't appreciate the value of comments in strings files. I'll work on a fix.

**Comment by gsantner** [comment]
Thanks for working on it!

To get an overview how other software resolve this: 
Maybe take a look at these 2 projects of mine: <https://github.com/froodyapp/froody-android/tree/master/app/src/main/res>, <https://github.com/Diaspora-for-Android/dandelion/tree/master/app/src/main/res>. They both use a translation service, which do add comments accordingly, support multiple strings.xml, and add missing files (if missing in a locale)

Example file for a language where nothing is translated yet: <https://github.com/Diaspora-for-Android/dandelion/blob/master/app/src/main/res/values-kn/strings-preferences.xml>

This seems to be pretty much the only public available standalone tool for the job; I see a lot of potential in this project
