### ISSUE TITLE
Cleanup modifies some localizations

### ISSUE THREAD

**Issue by gsantner** [jordanjoz1/android-localization-helper#4]
Heres an example string that gets modified by a cleanup:

`<string name="no_valid_path"><![CDATA[<font size="38"><center><h1> Ung&uumlltiger Pfad </h1></center></font> <font size="25"><br> Bitte die Login-Daten in den Einstellungen bearbeiten!</font>]]></string>`

--> 

`<string name="no_valid_path"> &lt;font size="38"&gt;&lt;center&gt;&lt;h1&gt; Ung&amp;uumlltiger Pfad &lt;/h1&gt;&lt;/center&gt;&lt;/font&gt; &lt;font size="25"&gt;&lt;br&gt; Bitte die Login-Daten in den Einstellungen bearbeiten!&lt;/font&gt;</string>
`

**Comment by jordanjoz1** [comment]
Ah, good find. I'll look into a fix soon. Thanks for the report!

**Comment by gsantner** [comment]
Closing some old stuff nobody seems to care about
